name: reverge merge from develop
on:
  push:
    branches: ["develop"]
  # workflow_call:
  # botによるpushで実行されないがPATを使いたくない
  # master PRマージ時の逆マージで明示的に呼び出せるようにする

jobs:
  reverse-merge-into-check:
    uses: ono5/parent-workflow/.github/workflows/reverse-merge.yml@release-0
    with:
      from-branch: develop
      into-branch: check
    secrets:
      github-app-private-key: ${{ secrets.BUILD_DEPLOY_PRIVATE_KEY }}
